services:
  ####### auth #######
  db_auth:
    image: 'postgres:17'
    container_name: db-auth
    ports:
      - "5433:5432"
    env_file:
      - auth/.env
    volumes:
      - ./data/auth:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10

  auth_backend:
    container_name: auth-backend
    build:
      context: ./auth
      dockerfile: docker/Dockerfile
    entrypoint: bash ./scripts/entrypoint.sh backend
    volumes:
      - ./auth/myapp:/opt/myapp
    ports:
      - "8001:8001"
    depends_on:
      db_auth:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  ###### catalog ######
  db_catalog:
    image: 'postgres:17'
    container_name: db-catalog
    ports:
      - "5434:5432"
    env_file:
      - catalog/.env
    volumes:
      - ./data/catalog:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10

  catalog_backend:
    container_name: catalog-backend
    build:
      context: ./catalog
      dockerfile: docker/Dockerfile
    entrypoint: bash ./scripts/entrypoint.sh backend

    volumes:
      - ./catalog/myapp:/opt/myapp
    ports:
      - "8002:8002"
    depends_on:
      db_catalog:
        condition: service_healthy

  smtp_backend:
    container_name: smtp-backend
    build:
      context: ./smtp
      dockerfile: docker/Dockerfile
    entrypoint: bash ./scripts/entrypoint.sh backend

    volumes:
      - ./smtp/myapp:/opt/myapp
    ports:
      - "8003:8003"
    depends_on:
      rabbit:
        condition: service_healthy

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Asia/Krasnoyarsk
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - 8080:1080
      - 1025:1025
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq-node
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.4-alpine
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"