from typing import Protocol

from myapp.application.dto.address import AddressCreate, AddressData


class IAddressGateway(Protocol):
    async def save(self, data: AddressCreate) -> AddressData: ...
    async def read_all_by_profile(self, profile_id: int) -> list[AddressData]: ...
    async def read_one(self, address_id: int) -> AddressData: ...
    async def delete(self, address_id: int) -> None: ...
    async def set_default(self, profile_id: int, address_id: int) -> None: ...
