{
 "title": "ГринАгро",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {}
   },
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "error, warning, info, debug, critical"
   },
   { "name": "log_keyword", "label": "Log Keyword" }
  ]
 },
 "panels": [
  { "title": "Статистика", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total errors by interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=~\"$container_name\", level=\"error\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (rate({container_name=~\"$container_name\", level=~\"$log_level\"} |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{.message_level}}"
    }
   ]
  },
  {
   "title": "Total warnings by interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=~\"$container_name\", level=\"warning\"} [$__range]))"
    }
   ]
  },
  { "title": "Логи", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container_name=~\"$container_name\", level=~\"$log_level\"} |= \"$log_keyword\" | json | line_format \"{{.container_name}}\\t{{.message_timestamp}}\\t{{.message_level}}\\t\\t{{.message_event}}\""
    }
   ]
  }
 ]
}