services:
  db:
    image: 'postgres:17'
    container_name: db
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10

  fmkv_backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: bash ./scripts/entrypoint.sh backend

    volumes:
      - ./myapp:/opt/myapp
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
